project_id = "gkowxzoadsljkpdzrlue"

[functions.ghl-create-contact]
verify_jwt = false

[functions.ghl-calendar]
verify_jwt = false

[functions.ghl-affiliate-webhook]
verify_jwt = false

[functions.create-partner-account]
verify_jwt = false

[functions.scorexer-intake]
verify_jwt = false
